#!/usr/bin/env bash
# Extract the contract specs (SCSpecEntry XDR, base64) from the built wasm
# files and write them into the app, so transactions can be composed offline
# with `contract.Spec` without fetching the spec from a network.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WASM_DIR="$ROOT/target/wasm32v1-none/release"
OUT="$ROOT/app/src/chain/specs.ts"
for c in grant_escrow policy_wallet; do
  [ -f "$WASM_DIR/$c.wasm" ] || { echo "missing $WASM_DIR/$c.wasm; run scripts/build.sh first" >&2; exit 1; }
done
ESCROW=$(stellar contract info interface --wasm "$WASM_DIR/grant_escrow.wasm" --output xdr-base64)
WALLET=$(stellar contract info interface --wasm "$WASM_DIR/policy_wallet.wasm" --output xdr-base64)
{
  echo "// Generated by scripts/gen-specs.sh from the built wasm files. Do not edit."
  echo "// Base64 stream of SCSpecEntry XDR values for each contract."
  echo "export const GRANT_ESCROW_SPEC ="
  echo "  \"$ESCROW\";"
  echo "export const POLICY_WALLET_SPEC ="
  echo "  \"$WALLET\";"
} > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
